// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /countries/{id}_get for http method type GET in rest-assured framework

RoostTestHash=49a6fdda39


*/

// ********RoostGPT********

if (response.statusCode() == default) {
