// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /countries/{id}_get for http method type GET in rest-assured framework

RoostTestHash=49a6fdda39


*/

// ********RoostGPT********

@Test  
public void countriesIdGet_Test() {
    this.setUp();

    for (Map<String, String> map : envList) {
        RestAssured.baseURI = map.get("BASE_URL");  

        // Adding some logging to help identify potential issues
        System.out.println("Testing with BASE_URL: " + map.get("BASE_URL"));
        System.out.println("Testing with id: " + map.get("id"));

        Response response = given()
            .pathParam("id", map.get("id") != null ? map.get("id") : "")
            .when()
            .get("/countries/{id}")  
            .then() 
            .extract().response();    

        // More logging
        System.out.println("Response code: " + response.statusCode());
        System.out.println("Response body: " + response.body().asString());
    }  
}
