// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /customers_get for http method type GET in rest-assured framework

RoostTestHash=757c7bf7d8


*/

// ********RoostGPT********

@Before
public void setUp() {
  TestdataLoader dataloader = new TestdataLoader();
  String[] envVarsList = {""}; // a semicolon was missing here
  envList = dataloader.loadData("src/test/java/org/agoncal/application/RoostTest/customersGetTest.csv", envVarsList);
}
