// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /customers/{id}_get for http method type GET in rest-assured framework

RoostTestHash=adad3d1e7b


*/

// ********RoostGPT********

if (response.statusCode() == default) {
  System.out.println("Description: successful operation");
}
