// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /customers/{id}_get for http method type GET in rest-assured framework

RoostTestHash=adad3d1e7b


*/

// ********RoostGPT********

/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /customers/{id}_get for http method type GET in rest-assured framework

RoostTestHash=adad3d1e7b
*/


// The error occurred due to the lack of a class, interface, or enum declaration.
// The Java code snippet provided is not within any class or method, which is causing the compilation error.
// Below is the corrected form of the code:

public class Test { // Class declaration added
    public void testStatusCode() { // Method declaration added
        if (response.statusCode() == default) {
            System.out.println("Description: successful operation");
        }
    }
}
