// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /items/{id}_get for http method type GET in rest-assured framework

RoostTestHash=cf8071d343


*/

// ********RoostGPT********

if (response.statusCode() == default) {
	System.out.println("Description: successful operation");
}
