// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /items_get for http method type GET in rest-assured framework

RoostTestHash=59ea07a9a1


*/

// ********RoostGPT********

String[] envVarsList = {""}
