// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /products_get for http method type GET in rest-assured framework

RoostTestHash=dad9f0399b


*/

// ********RoostGPT********

String[] envVarsList = {""}
