// ********RoostGPT********
/*
Test generated by RoostGPT for test java-rest-assued using AI Type Open AI and AI Model gpt-4

Test generated for /products_get for http method type GET in rest-assured framework

RoostTestHash=dad9f0399b


*/

// ********RoostGPT********
package org.agoncal.application.RoostTest;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;

public class productsGetTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      String[] envVarsList = {""};
      envList = dataloader.load("src/test/java/org/agoncal/application/RoostTest/productsGetTest.csv", envVarsList);
    }

  
    @Test  
    public void productsGet_Test() {
        this.setUp();
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "http://localhost:8080/applicationPetstore/rest";  
  
                Response responseObj = given()
				.queryParam("start", testData.get("start") != null ? testData.get("start") : "")
				.queryParam("max", testData.get("max") != null ? testData.get("max") : "")
                .when()
                .get("/products")  
                .then() 
                .extract().response(); 
              JsonPath response;
              String contentType = responseObj.getContentType();
              if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                String xmlResponse = responseObj.asString();
                JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                response = new JsonPath(jsonString);
        
              } else {  
                response = responseObj.jsonPath(); 
              }  
         
                if (responseObj.statusCode() == 200) {  
            JSONArray respoJsonArray = new JSONArray(responseObj.asString());  
  
            for (int it = 0; it < respoJsonArray.length(); it++) {  
              response = new JsonPath(respoJsonArray.getJSONObject(it).toString());  
                    
              if (response.get("id") != null) {  
                MatcherAssert.assertThat(response.get("id"), instanceOf(Integer.class));  
          }
      
              if (response.get("version") != null) {  
                MatcherAssert.assertThat(response.get("version"), instanceOf(Integer.class));  
          }
      
              if (response.get("name") != null) {  
                MatcherAssert.assertThat(response.get("name"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("name").length(), lessThanOrEqualTo(30));
  
                MatcherAssert.assertThat(response.getString("name").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.get("description") != null) {  
                MatcherAssert.assertThat(response.get("description"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("description").length(), lessThanOrEqualTo(3000));
  
                MatcherAssert.assertThat(response.getString("description").length(), greaterThanOrEqualTo(0));
  
          }
      
              if (response.get("category") != null) {      
              if (response.get("category.id") != null) {  
                MatcherAssert.assertThat(response.get("category.id"), instanceOf(Integer.class));  
          }
      
              if (response.get("category.version") != null) {  
                MatcherAssert.assertThat(response.get("category.version"), instanceOf(Integer.class));  
          }
      
              if (response.get("category.name") != null) {  
                MatcherAssert.assertThat(response.get("category.name"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("category.name").length(), lessThanOrEqualTo(30));
  
                MatcherAssert.assertThat(response.getString("category.name").length(), greaterThanOrEqualTo(1));
  
          }
      
              if (response.get("category.description") != null) {  
                MatcherAssert.assertThat(response.get("category.description"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("category.description").length(), lessThanOrEqualTo(3000));
  
                MatcherAssert.assertThat(response.getString("category.description").length(), greaterThanOrEqualTo(0));
  
          }
  
          }

            }  
          }
  
            }  
    }
}
