// Test generated by RoostGPT for test java-scenario-test using AI Type Open AI and AI Model gpt-4

/*
Test Scenario 1: Positive Test Case 
- Test Description: Validate the equals method when two objects are indeed the same.
- Input: Create two customer objects with the same login details.
- Expected Result: The equals method should return true since both objects are the same.

Test Scenario 2: Negative Test Case 
- Test Description: Validate the equals method when two objects are not the same.
- Input: Create two customer objects with different login details.
- Expected Result: The equals method should return false since both objects are not the same.

Test Scenario 3: Null Object Test Case
- Test Description: Validate the equals method when the object passed is null.
- Input: Pass a null object to the equals method.
- Expected Result: The equals method should return false since the object passed is null.

Test Scenario 4: Different Class Test Case
- Test Description: Validate the equals method when the object passed is of a different class.
- Input: Pass an object of a different class than customer to the equals method.
- Expected Result: The equals method should return false since the object passed is of a different class.

Test Scenario 5: Same Class Different Fields Test Case
- Test Description: Validate the equals method when the object passed is of the same class but different fields.
- Input: Create two customer objects with different fields except the login details.
- Expected Result: The equals method should return true since the login details are the same even though other fields are different.

Test Scenario 6: Null Login Field Test Case
- Test Description: Validate the equals method when the object's login field is null.
- Input: Create a customer object with a null login field and pass it to the equals method.
- Expected Result: The equals method should throw a NullPointerException.
*/
package org.agoncal.application.petstore.model;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class Customer_equals_f2d574000d_Test {

    private Customer testCustomer1;
    private Customer testCustomer2;
    private Customer testCustomer3;

    @Before
    public void setUp() {
        testCustomer1 = new Customer("John", "Doe", "jdoe", "password", "jdoe@example.com", new Address());
        testCustomer2 = new Customer("Jane", "Doe", "jdoe", "password", "jane.doe@example.com", new Address());
        testCustomer3 = new Customer("John", "Smith", "jsmith", "password", "jsmith@example.com", new Address());
    }

    @Test
    public void testEquals_SameCustomer() {
        assertTrue(testCustomer1.equals(testCustomer1));
    }

    @Test
    public void testEquals_DifferentCustomerSameLogin() {
        assertTrue(testCustomer1.equals(testCustomer2));
    }

    @Test
    public void testEquals_DifferentCustomerDifferentLogin() {
        assertFalse(testCustomer1.equals(testCustomer3));
    }

    @Test
    public void testEquals_NullCustomer() {
        assertFalse(testCustomer1.equals(null));
    }

    @Test
    public void testEquals_DifferentClass() {
        assertFalse(testCustomer1.equals(new String("jdoe")));
    }
}
